#! /usr/bin/bash

usage=$(cat << EOF
Usage: $0 <filename> <filename> ...
EOF
)

if [ "$#" -eq 0 ]; then
	echo "$usage"
	exit 1
fi

for f in "$@"; do
	lines=$(7z l -ba "$f" | awk '{print $6}' | cut -d/ -f1 | sort -u | wc -l)
	id=$(notify-send -p 'Extracting...')
	if [ "$lines" -ne 1 ]; then
		flag=-o"${f%.*}"
	fi
	7z x $flag "$f" && notify-send -r "$id" 'Done' -t 3000 || notify-send -r "$id" 'Failed'
done
