;;; http-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from http.el

(defvar-local http-hostname nil "\
Default hostname used when url is an endpoint.")
(put 'http-hostname 'safe-local-variable #'stringp)
(autoload 'http-edit-body-indirect "http" "\
Edit body in a indirect buffer." t)
(autoload 'http-curl-command "http" "\
Kill current http request as curl command." t)
(autoload 'http-process "http" "\
Process a http request.

If SYNC is non-nil executes the request synchronously.

(fn &optional SYNC)" t)
(autoload 'http-mode "http" "\
Major mode for HTTP client.

\\{http-mode-map}

(fn)" t)
(autoload 'http-response-mode "http" "\
Major mode for HTTP responses from `http-mode'

\\{http-response-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.http\\'" . http-mode))
(register-definition-prefixes "http" '("http-"))

;;; End of scraped data

(provide 'http-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; http-autoloads.el ends here
