# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]


# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.43.1"
"rocks-git.nvim" = "2.5.2"

nvim-treesitter = { git = "nvim-treesitter/nvim-treesitter" }
catppuccin = { git = "catppuccin/nvim" }

luasnip = "2.3.0"
cmp = { git = "hrsh7th/nvim-cmp" }
cmp-nvim-lsp = { git = "hrsh7th/cmp-nvim-lsp" }
cmp-buffer = { git = "hrsh7th/cmp-buffer" }
cmp-path = { git = "hrsh7th/cmp-path" }
cmp-cmdline = { git = "hrsh7th/cmp-cmdline" }
cmp_luasnip = { git = "saadparwaiz1/cmp_luasnip" }

mru = { git = "yegappan/mru" }
autoclose = { git = 'm4xshen/autoclose.nvim' }
luarocks = "3.11.1"
"rest.nvim" = "3.9.1"
"comment.nvim" = "0.8.0"
"oil.nvim" = "2.14.0"
nvim-web-devicons= "0.100"
conjure = "4.53.0"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"
rev = "efff286dd74c22f731cdec26a70b46e5b203c619"

[plugins."mason-lspconfig.nvim"]
git = "williamboman/mason-lspconfig.nvim"
rev = "v1.9.0"

[plugins."mason.nvim"]
git = "williamboman/mason.nvim"
rev = "v1.9.0"

[plugins."lsp-zero.nvim"]
git = "VonHeikemen/lsp-zero.nvim"

[plugins.nvim-lspconfig]
git = "neovim/nvim-lspconfig"
rev = "v1.6.0"

[plugins."kanagawa.nvim"]
git = "rebelot/kanagawa.nvim"

[plugins."NeoSolarized.nvim"]
git = "Tsuzat/NeoSolarized.nvim"

[plugins."komau.vim"]
git = "ntk148v/komau.vim"

[plugins."telescope.nvim"]
git = "nvim-telescope/telescope.nvim"

[plugins."plenary.nvim"]
git = "nvim-lua/plenary.nvim"

[plugins."telescope-file-browser.nvim"]
git = "nvim-telescope/telescope-file-browser.nvim"

[plugins.vim-table-mode]
git = "dhruvasagar/vim-table-mode"
rev = "v4.8.1^{}"

[plugins.nvim-treesitter-textobjects]
git = "nvim-treesitter/nvim-treesitter-textobjects"

[plugins.everforest]
git = "sainnhe/everforest"
rev = "v0.3.0^{}"

[plugins.vim-easy-align]
git = "junegunn/vim-easy-align"
rev = "2.9.7^{}"

[plugins."lualine.nvim"]
git = "nvim-lualine/lualine.nvim"
rev = "f4f791f67e70d378a754d02da068231d2352e5bc"
