;;; setup-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from setup.el

(autoload 'setup--make-docstring "setup" "\
Return a docstring for `setup'.")
(autoload 'setup "setup" "\
Configure feature or subsystem NAME.
BODY may contain special forms defined by `setup-define', but
will otherwise just be evaluated as is.
NAME may also be a macro, if it can provide a symbol.

(fn NAME &rest BODY)" nil t)
(function-put 'setup 'lisp-indent-function 1)
(put 'setup 'function-documentation '(setup--make-docstring))
(register-definition-prefixes "setup" '("setup-"))

;;; End of scraped data

(provide 'setup-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; setup-autoloads.el ends here
