[font]
size = 16
normal = ["JetBrains Mono"]

# [[font.normal]]
# family = "Fixedsys Excelsior"
# style = "Normal"
#
# [[font.bold]]
# family = "Fixedsys Excelsior"
# style = "Normal"

[[font.italic]]
family = "JetBrains Mono"
style = "Normal"
